env: %env%
root_dir: %root_dir%
cache_dir: %root_dir%/app/cache/%env%

twig.options:
  cache: %root_dir%/app/cache/%env%/twig

http_cache.cache_dir: %root_dir%/app/cache/%env%/httpcache

security.firewalls:
  unsecured:
    anonymous: true

monolog.logfile: %root_dir%/app/log/%env%.log

orm.proxies_dir: %root_dir%/app/cache/%env%/doctrine/proxies

profiler.cache_dir: %root_dir%/app/cache/%env%/profiler

assetic.path_to_web: %root_dir%/assets
assetic.options:
  auto_dump_assets: false
