locale: en
locale_fallback: en

form.secret: ThisTokenIsNotSoSecretChangeIt

swiftmailer.options:
  host: localhost
  port: 25
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~

db.options:
  driver: pdo_sqlite
  path: saxulum.db